### ISSUE TITLE
When viewing a memento, change the Mink icon to red

### ISSUE THREAD

**Issue by machawk1** [machawk1/Mink#102]
HVDS [suggested using the red Memento icon](https://twitter.com/hvdsomp/status/619602732320731141?cn=cmVwbHk%3D&refsrc=email) (for Mink) per the Memento for Chrome extension to be displayed when viewing a Memento. Changing the logo to red likely does not convey that a user is viewing an archived page. Any other suggestions, @phonedude @weiglemc ? Maybe a sepia, worn and torn Memento logo with the edges curling up? ;)

**Comment by phonedude** [comment]
the memento logo is already supposed to look aged (it has scratches, etc.) ;-)

I suggest staying in sync w/ what their tool does -- maybe even request the same image they use.  a fancy (future) solution would be allowing customizable images -- like frogs, beers, dogs in boats, etc.

**Comment by machawk1** [comment]
We have conditions in-place in the browserAction branch to change the icon to something specific. As of now, it's a place-holder (upside-down memento icon). The red icon does not indicate "this is a memento" to me. Since the logo already has scratches, maybe live web sites should not be displaying the memento logo and the memento logo (scratches and all) should be displayed when viewing a memento. When viewing an archived web page and seeing the memento icon, this indicates to me more that "the page I am viewing is a memento" than a red memento icon.
