### ISSUE TITLE
Reinstate access to download from Web Store

### ISSUE THREAD

**Issue by machawk1** [machawk1/Mink#250]
On January 25, 2018, Mink was removed from the Chrome Web store via Google because of a violation of the store's policies. The specific violation was not declared by Google, so I sought a further response and received it. On January 26, 2018, Google responded stating the issue was:

> Provide a link to your privacy policy in appropriate field in the Chrome Web Store Developer Console and on the inline installation page (if applicable). **Handle the data securely, including transmitting it via modern cryptography (TLS). If you’d like to re-submit it, please modify the item so that it complies with the policies, then re-publish it in your developer dashboard.** Please reply to this email for issues regarding this item removal.

From this I infer that the communication to MemGator and any other outside services needs to be HTTPS. I have contacted @ibnesayeed, who manages the MemGator instance in-question to determine if this is feasible. If so, we should be able to hit an HTTPS MemGator endpoint with some subtle tweaks in Mink.

**Comment by ibnesayeed** [comment]
I will try to setup TLS on our MemGator server soon.

**Comment by ibnesayeed** [comment]
MemGator is now serving both with and without TLS. You should be able to update references and submit it for review now.
