### ISSUE TITLE
Gracefully fail or fallback if ODUCS MemGator is down

### ISSUE THREAD

**Issue by machawk1** [machawk1/Mink#284]
...instead of returning 0 mementos or an error. This needs further testing to determine the current functionality.

**Comment by ibnesayeed** [comment]
Unless you are using unique MemGator features, you can fallback to LANL's aggregator or directly to IA's TimeMaps.

**Comment by machawk1** [comment]
@ibnesayeed Those are good options. LANL's interface has changed a few times with respect to their DIY vs WDI endpoints (Mink would need the latter). Having a second MemGator instance running elsewhere and publicly accessible would be ideal. Some code to de-duplicate is also due to be written.
