### ISSUE TITLE
Change wording of white/blacklist UI

### ISSUE THREAD

**Issue by machawk1** [machawk1/Mink#291]
The terms "whitelist" and "blacklist" can have negative connotations beyond how Mink uses them of inclusion and exclusion (resp) for processing. This feature should be changed to use different, less offensive names.

I am not sure of alternatives just yet that capture the spirit of the functionality.

**Comment by anjackson** [comment]
I think we use `allow` and `deny` lists.

**Comment by machawk1** [comment]
Thanks for the proactive reply, @anjackson. I'm not sure that `allow`/`deny` captures what is functionally occurring. By default, the logic is run on all URIs when visited. When a URI is added to the "blacklist", the logic is short-circuited and the URI not fully processed.

**Comment by anjackson** [comment]
Which makes me realised I was mistaken, our URL filtering uses `allow` and `block` (not 'deny`)! Does `block` make more sense?

**Comment by ibnesayeed** [comment]
> When a URI is added to the "blacklist", the logic is short-circuited and the URI not fully processed.

How about `ignore`?

**Comment by machawk1** [comment]
@anjackson `block` is probably closer to what is occurring than `deny` but I do not want to give the impression that access is being blocked, just that the URI is not being processed.

@ibnesayeed, `ignore` seems fitting. Thanks!
