### ISSUE TITLE
Mink has problems with resources with their own timegates/timemaps

### ISSUE THREAD

**Issue by phonedude** [machawk1/Mink#89]
I suspect this is b/c mink isn't processing non-json (i.e., link) timemaps.  it is also suspicious that it stops at 1000 -- this is probably just page 1.  

<img width="1440" alt="mink-date-problem" src="https://cloud.githubusercontent.com/assets/5322165/8632060/97cfea60-2758-11e5-9dd2-7fde6c463c4c.png">

**Comment by machawk1** [comment]
Thanks for submitting this bug on the official channel, @phonedude.

**Comment by phonedude** [comment]
I don't think this is closed.  here's the Tyrion page:  http://ws-dl-05.cs.odu.edu/demo/index.php/Tyrion_Lannister  I want "drop down" not "drill down", but "drop down" doesn't work.  I hit "drill down" several times and it kept adding to the display (see pic).  
<img width="1214" alt="mink-date-problems" src="https://cloud.githubusercontent.com/assets/5322165/8640167/f5803e66-28bc-11e5-8635-5d3811a4c193.png">

**Comment by machawk1** [comment]
The dropdown issue is a strange behavior. Can you reload the page to see if you get a consistent Mink UI? I cannot replicate (see attached).
![screen shot 2015-07-12 at 5 43 49 pm](https://cloud.githubusercontent.com/assets/2514780/8640188/ad869c76-28bd-11e5-839f-e12d6f32a19a.png)

I have the threshold of Dropdown to Miller Columns @ > 101 mementos. Do you really want to scroll through a list of 247 selections in a dropdown? Where do you think the threshold should be?

**Comment by phonedude** [comment]
I want to use "drop down" but it doesn't work, only "drill down" works.  I click on "drop down" and nothing.  Then I click on "drill down" again and it adds another part to the menu.  It will add another menu on each press of the "drill down" button.  

<img width="1214" alt="mink-drill-problems" src="https://cloud.githubusercontent.com/assets/5322165/8640215/874d4dd8-28be-11e5-97c3-dcefbd6b6bd6.png">

**Comment by machawk1** [comment]
Excellent. I created #92 and #93 to address these issues. Thanks for reporting!
