### ISSUE TITLE
on/off toggle needed

### ISSUE THREAD

**Issue by phonedude** [machawk1/Mink#90]
We talked about it (based on Liza's input), but Herbert also identified the need for it.  I think people are going to want this.

**Comment by machawk1** [comment]
Do you think a white/blacklist approach is best? Should we have a default list, e.g., gmail.com? @weiglemc

**Comment by phonedude** [comment]
First I'd add a toggle.  Then I'd add a w/b list to skip even when it's "on" (unless we have personal archives to access...  that would be cool, huh?  ;-)

**Comment by weiglemc** [comment]
Yep, I agree with this.

On Sun, Jul 12, 2015 at 5:43 PM, Michael L. Nelson <notifications@github.com

**Comment by machawk1** [comment]
This is similar (if not the exact same) as #56. Keeping this one open to emphasize priority.

**Comment by machawk1** [comment]
This has been fixed per #140 and will be included in the next release.
