### ISSUE TITLE
Getting stuck on some URLs

### ISSUE THREAD

**Issue by phonedude** [machawk1/Mink#91]
here's a URL that it just spins on, never resolving:

https://books.google.com/books?id=-vcTAQAAIAAJ

**Comment by machawk1** [comment]
With Mink version 1.3 (now released), this no longer gets "stuck". By the aforementioned, I presume that you meant that the logo continues to spin. Is this correct? This URI does not appear to have any archived instances (in archive.org), so the correct implementation should be to show the exclamation mark and provide the user an opportunity to archive the page, which Mink now does. Do you have another example where Mink gets stuck? If so, please re-open this ticket and provide the example URI.

**Comment by phonedude** [comment]
yeah, it would just spin.  now it goes to the "!" symbol.  thx.
