### ISSUE TITLE
Mementos aren't shown on first load, but only on reload

### ISSUE THREAD

**Issue by weiglemc** [machawk1/Mink#95]
When I first load the page, Mink says that it's not archived.  If I reload, then Mink finds the mementos.

http://www.professormesser.com/security-plus/sy0-401/sy0-401-course-index/
http://www.professormesser.com/security-plus/sy0-401/viruses-and-worms-2/

I've noticed this on several in this same site.

**Comment by machawk1** [comment]
I have noticed this as well but cannot reliably replicate it. I occasionally get HTTP 500s from the aggregator, which I believe is the source of this. If the Ajax request to the aggregator/archive fails, the "exclamation mark" icon is shown, giving the user an opportunity to submit the page. I don't believe this to be a bug in Mink until we can reliably replicate it. Thanks for the report!
